# @format

version: 2.1
orbs:
  node: circleci/node@1.1.6
  sonarcloud: sonarsource/sonarcloud@1.0.1
jobs:
  build-and-test-client-side:
    working_directory: ~/client
    executor:
      name: node/default
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - store_test_results:
          path: client/coverage
      - node/with-cache:
          cache-key: client/package.json
          dir: client/node_modules
          steps:
            - run:
                name: install npm dependancies
                command: cd client; npm install
            - run:
                name: run tests
                command: cd client; npm test
      - sonarcloud/scan
workflows:
  version: 2
  build-and-test-client-side:
    jobs:
      - build-and-test-client-side:
          context: SonarCloud
